### ISSUE TITLE
Mirror icons with RTL languages

### ISSUE THREAD

**Issue by kosratdev** [timmaffett/material_symbols_icons#39]
The icons are not mirrored when switching to an RTL language. I've checked the documentation but couldn't find any information on how to mirror the icons for RTL languages, so is there a way to do that?

**Comment by timmaffett** [comment]
Thank you for bringing this to my attention!
   I need to go through and determine which icons need to be reversed for RTL languages - My first pass will be to match the behavior for any icons which also exist in the `Icons` icon set.   
How this is done is that one a per-icon basis a `matchTextDirection: true` is added to the `IconData` declaration.  It looks like there are 303 icons in the legacy `Icons` set that do this.
   If you like send me a list of any icons which you think should mirror when in RTL language and I will ensure that these are correctly mirrored.

**Comment by timmaffett** [comment]
I have figured out that I can at least extract the information about which icons need to be reversed for RTL by examining one of the android XML files that is generated for each icon.
Example:
   [assignment_20px.xml example here](https://github.com/google/material-design-icons/blob/master/symbols/android/assignment/materialsymbolsoutlined/assignment_20px.xml)

These files contain a `android:autoMirrored="true"` attribute within the `<vector ...>` tag which indicates that the icon should be mirrored for RTL.   It would be nice if this information was elsewhere, but I have been unable to find it.

If need be I will make a script that grabs example XML files for all 3400+icons and extract this information.  Unfortunately the [official repo](https://github.com/google/material-design-icons) does not include some of this important information in a more friendly/accessible way.

**Comment by timmaffett** [comment]
I completed RTL support for the package a couple weeks ago but I have been too busy with work to get the new version pushed out.   
I am hoping to do so in the next few days- if you need it sooner just ping me here and I will get it done.

**Comment by kosratdev** [comment]
Thank you very much @timmaffet, for your hard work. Currently, I'm using both your package and the default one in Flutter, so when you publish it, I can completely depend on your package for material icons.

**Comment by timmaffett** [comment]
Hi @kosratdev    I have pushed the new version 4.2815.1 which has the Right To Left icon mirroring support  ! 🎉 

This adds the `matchTextDirection` to each of the appropriate icons - it was a little tricky to find out here to get this information, but in the end it worked out great because it also allowed me to add other icon metadata support which had been requested a long time ago.

Please give it a try and let me know!

**Comment by timmaffett** [comment]
@kosratdev Is everything working as you would expect ?

I would expect it to, but I would prefer outside confirmation from an actual user of a RTL language.

**Comment by timmaffett** [comment]
I am closing this issue as we now support RTL languages

**Comment by kosratdev** [comment]
Hello @timmaffett, I've used the latest version of the package (4.2874.0), but auto mirror icons still don't work. Look at the attached screen: 

I used this icon: `Symbols.chevron_right_rounded`, the same icon will be mirrored in the Icons package.

<img width="1206" height="1119" alt="Image" src="https://github.com/user-attachments/assets/b557671b-cff7-4f00-86c5-e0f4f4026d58" />

**Comment by kosratdev** [comment]
@timmaffett The problem hasn't been fixed yet! Could you please check it again?

**Comment by timmaffett** [comment]
Hi @kosratdev -  I am at a bit of a loss to what might be happening.   I extract the information for which icons need to be RTL reversed and then I add it to my `IconData` definitions like this:

```
  static const IconData do_disturb =
      IconDataOutlined(0xf08c, matchTextDirection: true);
```
Note the addition of `matchTextDirection: true` 

This is supposed to indicate to the framework that this particular icon should be reversed in the context of a RTL language.
Outside of this the actual reversing of the icons it is outside of my control as far as I know as far as I understand ?

If you wanted to make an example app we/I could investigate further and see if there is anything else that is missing.  If you do make an example please include some Icons from the regular set that do work and then some from Symbols that do not work.  Please also explicitly set the language to a RTL language.

I would be happy to help/investigate further from there.

-tim

**Comment by timmaffett** [comment]
Hello again @kosratdev,
   I read you earlier comment closer and I checked the icon `chevron_right_rounded` and this icon is not defined as a RTL matched text direction icon.
Only the icons that the designer has specified should match text direction are reversed in the context of a RTL language.

``` 
  static const IconData chevron_right_rounded = IconDataRounded(0xe5cc);
```

If you wanted this to be reversed you should be able to make your own copy of package and add the `matchTextDirection: true` argument to this icon's IconData definition.

You can search the symbols.dart file for the `matchTextDirection` argument to see which icons are specified as being a automatically reversed icon.

-tim

**Comment by kosratdev** [comment]
Hello @timmaffett, Thank you very for your explanation and your efforts on developing and maintaining this library. 

I've checked the `chevron_right_rounded` in the official Google repository and Flutter Icons Class. They both have `autoMirrored=true` and `matchTextDirection: true` as mentioned below: 

Google Official `chevron_right_rounded`
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960"
    android:tint="?attr/colorControlNormal"
    android:autoMirrored="true">
  <path
      android:fillColor="@android:color/white"
      android:pathData="M504,480L348,324Q337,313 337,296Q337,279 348,268Q359,257 376,257Q393,257 404,268L588,452Q594,458 596.5,465Q599,472 599,480Q599,488 596.5,495Q594,502 588,508L404,692Q393,703 376,703Q359,703 348,692Q337,681 337,664Q337,647 348,636L504,480Z"/>
</vector>
```

Icons Class
```
  /// <i class="material-icons md-36">chevron_right</i> &#x2014; material icon named "chevron right".
  static const IconData chevron_right = IconData(
    0xe15f,
    fontFamily: 'MaterialIcons',
    matchTextDirection: true,
  );
```

I don't know where you checked it, which led to you not finding those tags. Furthermore, you know that most of the apps now support RTL, so I think we need to fully support RTLs in this library.

**Comment by timmaffett** [comment]
Hi @kosratdev - Sorry for the delays in getting back to you, I have been having some deadlines at work and have been swamped.

I get the metadata for the Material Symbols Icons from a google api - it includes the RTL mirroring information (true/false) for each icon.  In the case of the `chevron_right`

```
  "chevron_right": {
    "name": "chevron_right",
    "version": 329,
    "popularity": 52143,
    "codepoint": 58828,
    "categories": [
      "UI actions"
    ],
    "tags": [
      "advance",
      "angle bracket",
      "arrow",
      "arrows",
      "caret",
      "chevron",
      "continue",
      "details",
      "direction",
      "expand",
      "forward",
      "greater than",
      "indicator",
      "more",
      "move",
      "navigate",
      "navigation",
      "next",
      "next page",
      "next track",
      "open",
      "play",
      "proceed",
      "progress",
      "right",
      "right arrow",
      "scroll",
      "slide",
      "transition"
    ]
  },
```

Note that there is a entry `"rtlAutoMirrored": true,` that is normally present for icons that should be mirrored.  In the case of `chevron_right` this is missing.  I appreciate that the Material Symbol `Icon` icons from the flutter sdk , which have many corresponding symbols, has this set to true.  I will have to figure out how to resolve this discrepancy.  I could take a inventory of all the Icons in `Icon` that have this set and where it is unset in the metadata for the Material Symbols Icons - and set it to true for those also ?  This is probably an issue for the Material Design repo but they are not the most pro-active in getting things figured out or resolved. I will also analyze looking at the svg file for the Material Symbols Icons in the repo and see if it is set there.


Here is an example from an icon that is indicated to be mirrored:

```json
"mobile_screen_share": {
    "name": "mobile_screen_share",
    "version": 329,
    "rtlAutoMirrored": true,
    "popularity": 353,
    "codepoint": 57575,
    "categories": [
      "Hardware"
    ],
    "tags": [
      "Android",
      "OS",
      "app",
      "application",
      "arrow",
      "cast",
      "cell",
      "connect",
      "device",
      "direction",
      "display",
      "export",
      "hardware",
      "iOS",
      "mirror",
      "mirroring",
      "mobile",
      "mobile application",
      "mobile screen share",
      "mobile share",
      "monitor",
      "output",
      "phone",
      "project",
      "rectangle",
      "right",
      "rounded rectangle",
      "screen",
      "screen sharing",
      "screencast",
      "send",
      "share",
      "share screen",
      "shortcut",
      "stream",
      "streaming",
      "tablet",
      "transfer",
      "tv",
      "wireless"
    ]
  },
```

**Comment by timmaffett** [comment]
..and I agree that this is important - I have spent many, many hours on getting the metadata incorporated and mistakenly thought it was resolved once I did that... darn it!

**Comment by timmaffett** [comment]
@kosratdev  I have found the bug that was causing the RTL settings for icons to be lost.  I determine this information by looking through each and every .SVG file for each icon to see if it has a RTL setting, and then adding this inofrmation to the meta data .  This was losing the information between builds.  (Because this takes a long time to retrieve the files from the server I was trtying to cache the info).   I have added a new mechanism so that it tracks the RTL icons each build so it is easy to check if any have been lost/changed inadvertantly.
   The new build on pub.dev should have all the icons set correctly.
   Thanks again for taking all this time to make sure this was correct!

**Comment by kosratdev** [comment]
Good to hear that 👏 well done @timmaffett. I will check it soon and let you know if there is any issue.

**Comment by timmaffett** [comment]
Thanks again @kosratdev !  Again, I am sorry for how long this took to get resolved - I had a huge deadline at work, which unfortunately had me in the Swift world dealing with Apple nonsense.
